# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # the name of an Azure artifacts feed
  artifactFeed: nyam-public 

strategy:
  matrix:
    # Python36:
    #  python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: pip install setuptools wheel twine
  displayName: Install build tools

- script: python setup.py sdist bdist_wheel
  displayName: Build package

- task: TwineAuthenticate@1
  displayName: Configure twine authentication
  inputs:
    artifactFeed: $(artifactFeed)

- script: 'twine upload -r $(artifactFeed) --config-file $(PYPIRC_PATH) dist/*'
  displayName: Publish artifacts

